package qiniu

// CertificateInfo represents a certificate in Qiniu
type CertificateInfo struct {
	CertID           string   `json:"certId"`
	Name             string   `json:"name"`
	UID              int64    `json:"uid"`
	CommonName       string   `json:"common_name"`
	DNSNames         []string `json:"dnsnames"`
	CreateTime       int64    `json:"create_time"`
	NotBefore        int64    `json:"not_before"`
	NotAfter         int64    `json:"not_after"`
	ProductType      string   `json:"product_type"`  // single, multi, wildcard
	CertType         string   `json:"cert_type"`     // DV, OV, EV
	Encrypt          string   `json:"encrypt"`       // RSA, ECC
	Enable           bool     `json:"enable"`
	AutoRenew        bool     `json:"auto_renew"`
	Renewable        bool     `json:"renewable"`
}

// ListCertificatesResponse represents the response from listing certificates
type ListCertificatesResponse struct {
	Marker string            `json:"marker"`
	Certs  []CertificateInfo `json:"certs"`
}

// UploadCertificateRequest represents a certificate upload request
type UploadCertificateRequest struct {
	Name       string `json:"name"`
	CommonName string `json:"commonName"`
	Pri        string `json:"pri"` // Private key
	Ca         string `json:"ca"`  // Certificate chain
}

// UploadCertificateResponse represents the response from uploading a certificate
type UploadCertificateResponse struct {
	CertID string `json:"certId"`
}

// ErrorResponse represents an API error response
type ErrorResponse struct {
	Code    int    `json:"code"`
	Message string `json:"error"`
}

// DomainInfo represents domain information from Qiniu
type DomainInfo struct {
	Name               string         `json:"name"`               // Domain name
	Type               string         `json:"type"`               // Domain type: normal/wildcard
	Platform           string         `json:"platform"`           // Platform type: web/download/vod/dynamic
	GeoCover           string         `json:"geoCover"`           // Geographic coverage: china/foreign/global
	Protocol           string         `json:"protocol"`           // Protocol: http/https
	CName              string         `json:"cname"`              // CNAME domain generated by Qiniu
	OperationType      string         `json:"operationType"`      // Last operation type
	OperatingState     string         `json:"operatingState"`     // Operation state: processing/success/failed/frozen/offlined
	OperatingStateDesc string         `json:"operatingStateDesc"` // Operation state description
	CreateAt           string         `json:"createAt"`           // Creation time (RFC3339)
	ModifyAt           string         `json:"modifyAt"`           // Last modified time (RFC3339)
	PareDomain         string         `json:"pareDomain"`         // Parent domain (for wildcard subdomains)
	Https              *HTTPSConfig   `json:"https"`              // HTTPS configuration
	IpTypes            uint           `json:"ipTypes"`            // IP protocol: 1=IPv4 only, 3=IPv4+IPv6
	KvTagList          []KVTag        `json:"kvTagList"`          // Key-Value tag list
	Source             *SourceConfig  `json:"source"`             // Origin configuration
	Cache              *CacheConfig   `json:"cache"`              // Cache policy
	Referer            *RefererConfig `json:"referer"`            // Referer anti-leech
	IPACL              *IPACLConfig   `json:"ipACL"`              // IP blacklist/whitelist
	TimeACL            *TimeACLConfig `json:"timeACL"`            // Timestamp anti-leech
	Bsauth             *BsauthConfig  `json:"bsauth"`             // Origin authentication
}

// HTTPSConfig represents HTTPS configuration
type HTTPSConfig struct {
	CertID      string   `json:"certId"`      // Certificate ID
	ForceHttps  bool     `json:"forceHttps"`  // Force HTTPS
	Http2Enable bool     `json:"http2Enable"` // Enable HTTP2
	TlsVersion  []string `json:"tlsVersion"`  // TLS versions
}

// SSLizeRequest represents a request to enable HTTPS for a domain
type SSLizeRequest struct {
	CertID      string   `json:"certId"`               // Certificate ID
	ForceHttps  bool     `json:"forceHttps"`           // Force HTTPS redirect
	Http2Enable bool     `json:"http2Enable"`          // Enable HTTP2
	TlsVersion  []string `json:"tlsVersion,omitempty"` // TLS versions
}

// KVTag represents a Key-Value tag
type KVTag struct {
	TagKey   string `json:"tagKey"`
	TagValue string `json:"tagValue"`
}

// SourceConfig represents origin configuration (placeholder)
type SourceConfig map[string]interface{}

// CacheConfig represents cache policy (placeholder)
type CacheConfig map[string]interface{}

// RefererConfig represents referer anti-leech configuration (placeholder)
type RefererConfig map[string]interface{}

// IPACLConfig represents IP blacklist/whitelist configuration (placeholder)
type IPACLConfig map[string]interface{}

// TimeACLConfig represents timestamp anti-leech configuration (placeholder)
type TimeACLConfig map[string]interface{}

// BsauthConfig represents origin authentication configuration (placeholder)
type BsauthConfig map[string]interface{}
